version: "3.8"

services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/letsencrypt:ro
      - ./nginx/www:/var/www/certbot:ro
      - ./shop:/var/www/shop:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./back/frontend/dist:/var/www/admin:ro
    depends_on:
      - api
    networks:
      - app-net

  api:
    build:
      context: ./back/server
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgres://denisbiceps:12345678@db:5432/zelenyeusy
    volumes:
      - ./shop:/app/shop:ro
    depends_on:
      - db
    networks:
      - app-net

  db:
    image: postgres:15-alpine
    container_name: postgresDataBase
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - app-net

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
