services:
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    user: "0"
    restart: unless-stopped
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./monitoring/alloy-config.alloy:/etc/alloy/config.alloy:ro
      - ./monitoring/data/alloy:/var/lib/alloy/data
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: run --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    networks:
      - site_app-net
    healthcheck:
      test: ["CMD", "alloy", "compile", "/etc/alloy/config.alloy"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s

  loki:
    image: grafana/loki:3.0.0
    user: "root"
    container_name: loki
    restart: unless-stopped
    volumes:
      - ./monitoring/loki-config.yaml:/etc/loki/local-config.yaml
      - ./monitoring/data/loki:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - site_app-net
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://127.0.0.1:3100/ready | grep -q 'ready'" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    env_file:
      - .env.monitoring
    ports:
      - "127.0.0.1:3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:?GRAFANA_PASSWORD is required}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:?GRAFANA_USER is required}
    volumes:
      - ./monitoring/data/grafana:/var/lib/grafana
      - ./monitoring/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    networks:
      - site_app-net
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://127.0.0.1:3000/api/health | grep -q 'ok'" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s

networks:
  site_app-net:
    external: true