INSERT INTO products (id, name, description, full_description, price, image, group_name, type, subtype, variety, volume, stock, tags) VALUES
                                                                                                                                          ('gortenziya-candybelle', 'Гортензия "Candybelle Stand Up Pink"', 'Компактная древовидная', 'Полное описание...', 1300, '/images/gortenziya-candybelle.jpg', 'garden', 'gortenziya', 'drevovidnaya', 'candybelle', 'Контейнер 5 л', 4, ARRAY['popular','new']),
                                                                                                                                          ('gortenziya-pinky-winky', 'Гортензия метельчатая Pinky Winky', 'Двухцветные соцветия', '', 1400, '/images/pinky.jpg', 'garden', 'gortenziya', 'metelchataya', 'pinky-winky', 'Контейнер 5 л', 7, ARRAY['popular']),
                                                                                                                                          ('gortenziya-annabelle', 'Гортензия Annabelle', 'Белые шары', '', 1250, '/images/annabelle.jpg', 'garden', 'gortenziya', 'drevovidnaya', 'annabelle', 'Контейнер 3 л', 5, '{}'),
                                                                                                                                          ('roza-black-magic', 'Роза Black Magic', 'Бархатная темно-красная', '', 950, '/images/black-magic.jpg', 'garden', 'roza', 'chaynaya', 'black-magic', 'Контейнер 2 л', 12, ARRAY['popular']),
                                                                                                                                          ('roza-kerio', 'Роза Kerio', 'Ярко-желтая', '', 900, '/images/kerio.jpg', 'garden', 'roza', 'chaynaya', 'kerio', 'Контейнер 2 л', 10, '{}'),
                                                                                                                                          ('roza-avalanche', 'Роза Avalanche', 'Белая срезочная', '', 980, '/images/avalanche.jpg', 'garden', 'roza', 'chaynaya', 'avalanche', 'Контейнер 2 л', 8, ARRAY['new']),
                                                                                                                                          ('pion-sarah', 'Пион Sarah Bernhardt', 'Классический розовый', '', 1800, '/images/sarah.jpg', 'garden', 'pion', 'travyanistiy', 'sarah-bernhardt', 'Корень', 6, ARRAY['popular']),
                                                                                                                                          ('pion-coral', 'Пион Coral Charm', 'Коралловый', '', 1950, '/images/coral.jpg', 'garden', 'pion', 'travyanistiy', 'coral-charm', 'Корень', 4, '{}'),
                                                                                                                                          ('pion-bartzella', 'Пион Bartzella', 'ИТО-гибрид желтый', '', 2500, '/images/bartzella.jpg', 'garden', 'pion', 'ito', 'bartzella', 'Корень', 3, ARRAY['new']),
                                                                                                                                          ('fialka-optimara', 'Фиалка Optimara', 'Комнатная', '', 450, '/images/optimara.jpg', 'indoor', 'fialka', 'saintpaulia', 'optimara', 'Горшок 9см', 20, ARRAY['popular']),
                                                                                                                                          ('fialka-shanson', 'Фиалка Le-Shanson', 'Махровая', '', 480, '/images/shanson.jpg', 'indoor', 'fialka', 'saintpaulia', 'le-shanson', 'Горшок 9см', 15, '{}'),
                                                                                                                                          ('orhideya-white', 'Орхидея Phalaenopsis White', 'Белая', '', 2100, '/images/orchid-white.jpg', 'indoor', 'orhideya', 'phalaenopsis', 'white', 'Горшок 12см', 9, ARRAY['popular']),
                                                                                                                                          ('orhideya-dendrobium', 'Орхидея Dendrobium', 'Нобиле', '', 2300, '/images/dendro.jpg', 'indoor', 'orhideya', 'dendrobium', 'nobile', 'Горшок 12см', 5, '{}'),
                                                                                                                                          ('tulpan-red', 'Тюльпан Triumph Red', 'Красный', '', 120, '/images/tulpan-red.jpg', 'bulbs', 'tulpan', 'triumph', 'red', 'Луковица 10шт', 100, ARRAY['popular']),
                                                                                                                                          ('tulpan-pink', 'Тюльпан Darwin Pink', '', '', 130, '/images/tulpan-pink.jpg', 'bulbs', 'tulpan', 'darwin', 'pink', 'Луковица 10шт', 80, '{}')
-- ДОБАВЬ ЕЩЕ 15 ПО АНАЛОГИИ, чтобы было 30
    ON CONFLICT (id) DO NOTHING;