name: CI

on:
  pull_request:
    branches:
      [ main,  dev ]
  push:
    branches:
      [ main ]

jobs:
  admin_frontend:
    name: Админ панель lint & build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back/frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: back/frontend/package-lock.json
      - name: Установка зависимостей
        run: npm ci
      - name: Проверка линтером (Lint)
        run: npm run lint
      - name: Тестовая сборка проекта (Build)
        run: npm run build

  shop_frontend:
    name: Фронт магазина lint & build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shop
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: shop/package-lock.json

      - name: Установка зависимостей
        run: npm ci

      - name: Проверка линтером (Lint)
        run: npm run lint

  api_backend:
    name: Апи
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back/server/
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: back/server/package-lock.json

      - name: Установка зависимостей
        run: npm ci

      - name: Проверка линтером (Lint)
        continue-on-error: true
        run: npm run lint

      - name: Тесты
        run: npm test

  docker_api:
    name: Докерфайл апи
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Билд апи образа
        run: docker build -t docker_api_test back/server
  
  docker_compose:
    name: Докер
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.yml:docker-compose.ci.yml
    steps:
      - uses: actions/checkout@v4

      - name: Подготовка env
        run: cp .env.example .env

      - name: Проверка конфига Docker Compose
        run: docker compose config

      - name: Проверка сборки Docker Compose
        run: docker compose build

      - name: Поднятие сервисов
        run: docker compose up -d

      - name: Ждем Db
        run: |
          for i in {1..30}; do
                  status=$(docker inspect --format='{{.State.Health.Status}}' postgresDataBase)
                  if [ "$status" = "healthy" ]; then
                      exit 0
                  fi
                  sleep 2
                done
                docker compose logs
                exit 1

      - name: Ждем Api
        run: |
          for i in {1..30}; do
                  status=$(docker inspect --format='{{.State.Health.Status}}' api)
                  if [ "$status" = "healthy" ]; then
                      exit 0
                  fi
                  sleep 2
                done
                docker compose logs
                exit 1

      - name: Проверяем /api/products
        run: curl -f http://localhost/api/products

  nginx_config:
    name: Nginx test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build API
        run: docker build -t my-api:latest -f ./back/server/Dockerfile ./back/server

      - name: Run API
        run: docker run -d --name api -p 3000:3000 my-api:latest

      - name: Настройка локального DNS для теста
        run: echo "127.0.0.1 api" | sudo tee -a /etc/hosts

      - name: Устанавливаем Nginx
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx

      - name: Копируем nginx.conf
        run: sudo cp nginx/nginx.ci.conf /etc/nginx/nginx.conf

      - name: Создаём директорию и файлы
        run: |
          sudo mkdir -p /etc/letsencrypt/live/zelenyeusy.ru
          sudo touch /etc/letsencrypt/live/zelenyeusy.ru/privkey.pem \
                /etc/letsencrypt/live/zelenyeusy.ru/fullchain.pem

      - name: Проверка
        run: sudo nginx -t

      - name: Остановить API
        if: always()
        run: docker stop api || true


  deploy:
    name: Деплой
    runs-on: ubuntu-latest

    # КЛЮЧЕВОЙ МОМЕНТ: Ждем успешного завершения ВСЕХ проверок
    needs: [ admin_frontend, shop_frontend, api_backend, docker_api, docker_compose, nginx_config ]

    # ДОПОЛНИТЕЛЬНОЕ УСЛОВИЕ: Физически отправляем код на сервер ТОЛЬКО при пуше в main.
    # При обычном Pull Request (до слияния) деплой запускаться НЕ БУДЕТ.
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Выполнить деплой-скрипт на сервере
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: bash ~/zelenyeusy/deploy.sh